---
- hosts: all
  gather_facts: no

  tasks:

    - name: set timezone to Asia/Singapore
      timezone:
        name: Asia/Singapore

    - name: ensure necessary packages are installed
      yum:
        name:
          - ipmitool
          - watchdog
          - tuned
        state: present

    - name: ensure ipmi_watchdog kernel module is loaded
      modprobe:
        name: ipmi_watchdog
        state: present

    - name: ensure ipmi_watchdog kernel module loads at boot
      lineinfile:
        dest: /etc/modules-load.d/ipmi_watchdog.conf
        create: yes
        line: ipmi_watchdog

    - name: ensure watchdog-device is set to /dev/watchdog in watchdog.conf
      lineinfile:
        dest: /etc/watchdog.conf
        regexp: watchdog-device\s+=
        line: watchdog-device        = /dev/watchdog

    - name: ensure watchdog.service is enabled and started
      systemd:
        name: watchdog.service
        state: started
        enabled: yes

- hosts: osds
  gather_facts: no

  tasks:

    - name: get active tuned profile
      shell: "tuned-adm profile | awk '/Current active profile: / {print $4}'"
      changed_when: false
      register: tuned_profile

    - name: ensure active tuned profile is network-throughput
      shell: tuned-adm profile network-throughput
      when: tuned_profile.stdout != "network-throughput"
