---
- hosts: all
  gather_facts: no

  tasks:

    - name: collect hardware facts to determine system vendor
      setup:
        gather_subset:
          - hardware

    - name: gather package facts to determine if ipmitool is installed
      when: ansible_facts['system_vendor'] == 'Supermicro'
      package_facts:
        manager: auto

    - name: install ipmitool
      when: ansible_facts['system_vendor'] == 'Supermicro' and ansible_facts.packages["ipmitool"] is undefined
      yum:
        name: ipmitool
        state: latest

    - name: disable bmc fan control (fans will run a full speed for a few seconds)
      when: ansible_facts['system_vendor'] == 'Supermicro'
      shell: ipmitool raw 0x30 0x45 0x01 0x01

    - name: set fans in system zone to 25%
      when: ansible_facts['system_vendor'] == 'Supermicro'
      shell: ipmitool raw 0x30 0x70 0x66 0x01 0x00 0x19

    - name: set fans in peripheral zone to 50%
      when: ansible_facts['system_vendor'] == 'Supermicro'
      shell: ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x32
