---
- hosts: all
  gather_facts: no

  tasks:

    - name: collect hardware facts to determine system vendor
      setup:
        gather_subset:
          - hardware

    - name: ensure ipmitool is installed
      when: ansible_facts['system_vendor'] == 'Supermicro'
      yum:
        name: ipmitool
        state: present

    - name: get bmc fan mode
      when: ansible_facts['system_vendor'] == 'Supermicro'
      command: ipmitool raw 0x30 0x45 0x00
      changed_when: false
      register: fan_mode

    - name: set bmc fan mode fact
      set_fact:
        fan_mode: "{{ fan_mode.stdout | trim }}"
      when: ansible_facts['system_vendor'] == 'Supermicro'
    
    - name: set bmc fan mode to full speed (to enable manual control)
      when: ansible_facts['system_vendor'] == 'Supermicro' and fan_mode != '01'
      shell: ipmitool raw 0x30 0x45 0x01 0x01

    - name: set fans in system zone to 25%
      when: ansible_facts['system_vendor'] == 'Supermicro'
      shell: ipmitool raw 0x30 0x70 0x66 0x01 0x00 0x19

    - name: set fans in peripheral zone to 25%
      when: ansible_facts['system_vendor'] == 'Supermicro'
      shell: ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x19
